topi314/LavaSrc

main/src/main/java/com/github/topisenpai/lavasrc/deezer/DeezerAudioSourceManager.java

Fix NPE when searching by isrc

---

main/src/main/java/com/github/topisenpai/lavasrc/mirror/MirroringAudioTrack.java

All classes now use AudioReference.NO_TRACK instead of "null". However, there was a place where "null" was still expected. Because of this, there was only search by ISRC. The search by "Query" was ignored. Fixed.

Fixed search by Query provider

---

README.md
application.yml.example
main/build.gradle
main/src/main/java/com/github/topisenpai/lavasrc/applemusic/AppleMusicSourceManager.java
plugin/build.gradle
plugin/src/main/java/com/github/topisenpai/lavasrc/plugin/AppleMusicConfig.java
plugin/src/main/java/com/github/topisenpai/lavasrc/plugin/LavaSrcPlugin.java

This is kind of a dirty workaround tbh
regexing the token out of a js file is terrible and is likely to break again
if you have any better idea feel free to suggest.
I added a config option to bypass the auto fetching. As of now their token is valid until 23th jan 2023.
If it breaks you can just extract the jwt token yourself and override it basically

fix apple music token fetching

---

main/src/main/java/com/github/topisenpai/lavasrc/yandexmusic/YandexMusicSourceManager.java

Fix error when track doesn't have cover
Fix error when track is not available
Fix error when track doesn't include in any albums (for example user uploaded track manually)

Some fixes for yandex music which led to an error when loading a track or playlist

---

README.md
application.yml.example

`dzsearch` as mentioned below is the actual query prefix for deezer search. The example uses `scsearch` but commented as if that is deezer.

Use dzsearch in the example when mentioning deezer

---

main/build.gradle

I am encountering this compiler error with LavaSrc as a dependency:
```
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
class com.github.topi314.lavasrc.deezer.DeezerAudioSourceManager, unresolved supertypes: com.github.topi314.lavasearch.AudioSearchSourceManager
Adding -Xextended-compiler-checks argument might provide additional information.
e: file:///home/freya/git/tenshi/tenshi/src/main/java/fredboat/config/AudioPlayerManagerConfiguration.kt:296:74 Cannot access 'com.github.topi314.lavasearch.AudioSearchSourceManager' which is a supertype of 'com.github.topi314.lavasrc.deezer.DeezerAudioSourceManager'. Check your module classpath for missing or conflicting dependencies
```
The problem appears to be that …

Expose lavasearch under the api scope

---

README.md

The maven and gradle imports had lavasrc-protocol instead of lavasrc-plugin, as well as maven didn't have a id for repository.

Fix README.md incorrect imports

---

main/src/main/java/com/github/topi314/lavasrc/applemusic/AppleMusicSourceManager.java
main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java

Added support for manually uploaded tracks (only those uploaded by the token owner available)
Implemented recognition of track links without specifying the album, e.g., https://music.yandex.ru/track/75370207
Now, if a track has multiple artists, all of them will be listed in the author field instead of just one.

Enhancements in Track Handling and Artist Recognition for Yandex Music

---

main/src/main/java/com/github/topi314/lavasrc/deezer/DeezerAudioSourceManager.java

This allows lavasrc to process more than the first 25 tracks in a Deezer playlist.
This removes the API call to Deezer at `/playlist/:id/tracks` and uses the already fetched data from `/playlist/:id` instead. It appears that the former is paginated, returning 25 results, whereas the latter returns the full dataset without pagination.
Here is a playlist you can use for testing: https://www.deezer.com/en/playlist/11958416461?host=5617782001&deferredFl=1
The above playlist yielded 243/260 tracks in my testing with this patch.

Fix not parsing full Deezer playlists

---

main/src/main/java/com/github/topi314/lavasrc/flowerytts/FloweryTTSAudioTrack.java

- Removes the need to instantiate tracks based on reflection hacks, and uses an enum to map formats to their respective audio track classes
- Improves code readability
- Slight optimisation in that `queryParams` is not iterated for each iteration of `config.entrySet()`
- Removes a stray `println` in favour of a `log.debug`

Clean up FloweryTTS AudioTrack

---

main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicAudioTrack.java

The error was caused by selecting the first track without checking the codec.

Fixed mp3 frame not found.

---

README.md
application.example.yml
main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
plugin/src/main/java/com/github/topi314/lavasrc/plugin/LavaSrcPlugin.java
plugin/src/main/java/com/github/topi314/lavasrc/plugin/YandexMusicConfig.java

* The recommendation logic for the track is implemented
* Added query argument to get full tracks without pain and checks
* Fixed parseCoverUri
* Wrote load limits for playlists, artists, albums

Yandex Music Updates

---

main/src/main/java/com/github/topi314/lavasrc/spotify/SpotifySourceManager.java
main/src/main/java/com/github/topi314/lavasrc/spotify/SpotifyTokenTracker.java

currently untested, moves token fetching to a dedicated token tracker class, and allows falling back to the public token fetching if client id and client secret are unspecified.
perhaps token fetching with spdc fetching could be moved to the token tracker

allow fetching public tokens in place of app tokens

---

README.md
application.example.yml
main/src/main/java/com/github/topi314/lavasrc/spotify/SpotifyAudioTrack.java
main/src/main/java/com/github/topi314/lavasrc/spotify/SpotifySourceManager.java
plugin/src/main/java/com/github/topi314/lavasrc/plugin/LavaSrcAudioPluginInfoModifier.java
plugin/src/main/java/com/github/topi314/lavasrc/plugin/LavaSrcPlugin.java
plugin/src/main/java/com/github/topi314/lavasrc/plugin/SpotifyConfig.java

Added support for Spotify local files and included an option for this feature in the configuration.

Local File Support

---

main/src/main/java/com/github/topi314/lavasrc/spotify/SpotifySourceManager.java

This change adds the provider name information to the lyrics retrieved from Spotify. 
As this is my first-ever pull request, please let me know if there is anything wrong.

Add more detailed lyrics provider names for lyrics retrieved from Spotify

---

README.md
main/src/main/java/com/github/topi314/lavasrc/deezer/DeezerAudioSourceManager.java

```py
async def fetch_deezer_recos(
session_id: str, api_token: str, track_id: int
) -> Dict[str, Any]:
url = f"https://www.deezer.com/ajax/gw-light.php?method=song.getSearchTrackMix&input=3&api_version=1.0&api_token={api_token}"
data = {"sng_id": track_id, "start_with_input_track": "true"}
headers = {"Cookie": f"sid={session_id}"}
request = httpx.Request(method="POST", url=url, json=data, headers=headers)
return await fetch_as_json(request)
```
Now, Deezer has a recommendations API that allows fetching recommendations without user authentication using the track ID. This is particularly helpful since Spotify stopped providing recommendations due to recent API changes, making Deezer a viable replacement for Spotify in this regard.

added support for fetching recommendations from deezer

---

main/src/main/java/com/github/topi314/lavasrc/applemusic/AppleMusicSourceManager.java
main/src/main/java/com/github/topi314/lavasrc/applemusic/AppleMusicTokenManager.java

actually make apple useful without a key

add apple music auto token extraction

---

plugin/src/main/java/com/github/topi314/lavasrc/plugin/LavaSrcPlugin.java

@RequestBody was missing here, which prevented the config from being updated.

Fix updating config via rest

---

main/src/main/java/com/github/topi314/lavasrc/deezer/DeezerAudioSourceManager.java

Hi, I’m no an expert, not on GitHub this is my first PR. 
I noticed this error when trying to get Deezer recommendations using dzrec in LavaPlayer:
`Failed to get recommendations: {"VALID_TOKEN_REQUIRED":"Invalid CSRF token"}`
I fixed it by adding dzr_uniq_id to the Cookie header along with sid.
Please review :)

Fix "Invalid CSRF token" err for the Deezer recommendations

---

README.md
main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java

Adds support for new URLs type containing UUIDs.
Tested with:
- https://music.yandex.ru/playlists/e1bb61b5-360d-e3c5-124c-ef58d981ca7d
- https://music.yandex.ru/playlists/lk.a4423efa-296b-4f9d-9e24-61907a8ae2f1
- https://music.yandex.ru/playlists/lk.4ce94cae-0fe0-43f3-8996-1ec504adbf98?utm_source=web&utm_medium=copy_link
- https://music.yandex.ru/playlists/ps.1105710d-6405-47ff-b011-c7242318ba53?utm_source=web&utm_medium=copy_link
Old URL format still works as expected.

Add support for new Yandex Music playlist URLs
